### PR TITLE
Update the Dockerfile for stackdriver-metrics-adapter to apply capabi…

### PR DESCRIPTION
**Pull request by vinayakankugoyal**
…lities to adapter binary so that it can bind to privileged ports without needing to be run as root.

### CODE REVIEW

**Comment by serathius** [comment]
I think this is overkill, I would prefer to change the default port to 4443

**Comment by vinayakankugoyal** [comment]
> I think this is overkill, I would prefer to change the default port to 4443

Thanks will do! Closing this PR.

**Pull request closed without merging**
