### PR TITLE
#52 setting 'DOUBLE' as the default type

### PR DESCRIPTION
**Pull request by acondrat**

### CODE REVIEW

**Comment by acondrat** [comment]
I signed it!

**Comment by loburm** [comment]
@acondrat have you checked what will happen if we try to rewrite value type for already existing metric in stackdriver? Currently we already have prometheus-to-sd usages that we don't want to break.

**Comment by acondrat** [comment]
@loburm looks like the valueType is not updated. I had to manually recreate the metric descriptor with  [projects.metricDescriptors/delete](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.metricDescriptors/delete) and [projects.metricDescriptors/create](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.metricDescriptors/create)

Simply deleting the metricDescriptor was not enough. For some reason it keeps using the old (INT64) valueType. I suspect [projects.metricDescriptors/list](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.metricDescriptors/list) is cached.

**Comment by loburm** [comment]
In such case we can't merge this PR yet, because some of the existing metrics are going to be broken. I'll try to come up with better solution.

**Comment by filipe-cantarelli** [comment]
As far as I remember when I was looking at the issue, this change will only affect new metrics(metrics that don't have a metricDescriptor yet). For any old metric, the type specified in the metricDescriptor will be used instead.

**Comment by loburm** [comment]
That's not true. If original metric descriptor is missing from the cache, then we are going to use the default one. That's a case for GKE metrics that are writable but not readable.

**Pull request closed without merging**
