### PR TITLE
Allow for custom metric endpoints

### LINKED ISSUE #108: non standard url for prom metrics
Is there a way to pull prom metrics from http://localhost/xyx instead of always defaulting to  http://localhost/metrics ?

When I specify 
```
 command:
        - /monitor
        - --source=:http://localhost:80/promMetrics
        - --stackdriver-prefix=custom.googleapis.com
        - --pod-id=$(POD_ID)
        - --namespace-id=$(POD_NAMESPACE)


```
It still defaults to /metrics

### PR DESCRIPTION
**Pull request by deejay1**
Spring 5 by default the actuator endpoint /status/prometheus,
so we should allow for setting it in config.
The default /metrics is left alone. Fixes #108.

### CODE REVIEW

**Comment by deejay1** [comment]
Fixed conflicts

**Comment by deejay1** [comment]
Any hope on this? We're near one month now from the initial commit and two months since #108 was opened ;)

**Comment by deejay1** [comment]
@loburm Added a defaultMetricsPath const and used it throughout the test file also. Unfortunately the build is broken probably because https://github.com/golang/lint/issues/396 :(

**Comment by loburm** [comment]
I have rerun by myself, everything looks good.

Thanks once again.

**Pull request merged**
