### PR TITLE
Add testing utility - a pod that exports custom metric defined by flags

### PR DESCRIPTION
**Pull request by kawych**

### CODE REVIEW

**Comment by piosz** [comment]
Looks good. Please:
- add a few lines of comments [here](https://github.com/GoogleCloudPlatform/k8s-stackdriver/pull/53/files#diff-d1c371780e939d495b3a7fd7fb7e62d2R32) what it does
- change the name to more meaningful - it's SD specific, it's and exporter not exposer, and it doesn't do anything reasonable, so how about `sd_dummy_exporter`?

**Comment by kawych** [comment]
Comments applied.

**Comment by piosz** [comment]
FYI @mwielgus

**Comment by piosz** [comment]
Please squash the commits and feel free to merge on green

**Pull request merged**
