### PR TITLE
Remove version tag from the GCR reference

### PR DESCRIPTION
**Pull request by tomoe**
Otherwise we'd have to update README at every release.

### CODE REVIEW

**Comment by x13n** [comment]
Can we just keep the latest tag in one place? The easiest solution seems to be to just write in the readme to look into Makefile and read the TAG var.

**Comment by crassirostris** [comment]
Well, just removing a tag makes it confusing: we don't export the `latest` tag, so trying to download such an image will fail

Maybe we should phrase it ``Look at the following link: `https://gcr.io/google-containers/prometheus-to-sd` and pick the latest image``

**Comment by tomoe** [comment]
> Maybe we should phrase it Look at the following link: `https://gcr.io/google-containers/prometheus-to-sd` and pick the latest image

+1
Also, why not adding ":latest" tag when the newest release is pushed?

**Comment by tomoe** [comment]
Updated the working with @crassirostris 's suggestion.

**Comment by x13n** [comment]
Thanks. Can you also make this link a link? Right now one has to copy&paste it.

**Comment by tomoe** [comment]
@x13n Done!

**Comment by x13n** [comment]
Thanks!

**Pull request merged**
