### PR TITLE
Rebase kubelet-to-gcm to distroless

### PR DESCRIPTION
**Pull request by yuwenma**
This is part of the effort described in kep kubernetes/enhancements#900

### CODE REVIEW

**Comment by yuwenma** [comment]
Gentle ping

**Comment by x13n** [comment]
Thanks for the PR and apologies for lack of response - I was away for a week.

The change looks good to me, although I don't understand what healthcheck you are referring to in the title.

**Comment by yuwenma** [comment]
> Thanks for the PR and apologies for lack of response - I was away for a week.
> 
> The change looks good to me, although I don't understand what healthcheck you are referring to in the title.

Oops. I mean the kubelet-to-gcm container. (Copy-paste the wrong line from my list)

**Comment by x13n** [comment]
Now it makes sense, thanks!

**Pull request merged**
