### PR TITLE
Upgrade fluent-plugin-detect-exceptions to latest

### PR DESCRIPTION
**Pull request by zombiezen**
Fixes Go panic parsing bugs addressed in GoogleCloudPlatform/fluent-plugin-detect-exceptions#18

### CODE REVIEW

**Comment by x13n** [comment]
Thanks for the PR! Can you also bump the version tag in Makefile?

**Comment by crassirostris** [comment]
Awesome! Please squash commits and I will merge

**Comment by zombiezen** [comment]
Done.

**Comment by crassirostris** [comment]
Thanks! Now you can update the image in the K8s repo

**Pull request merged**
